# Generated by Django 2.0.6 on 2019-04-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='your_email',
        ),
    ]
