# Generated by Django 2.0.6 on 2019-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phoneno',
            field=models.CharField(max_length=11),
        ),
    ]
